[package]
name = "swloop"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"
